name: Generate PlantUML Diagrams

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t plantuml-image .

    - name: Generate Diagrams
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/src:/src \
          -v ${{ github.workspace }}/out:/out \
          plantuml-image \
          java -DPLANTUML_LIMIT_SIZE=8192 -Djava.compiler=NONE -jar /usr/share/java/plantuml-1.2023.12.jar -o /out -quiet -tpng /src/**/*.puml

    - name: Upload Diagrams
      uses: actions/upload-artifact@v4
      with:
        name: plantuml-diagrams
        path: 'out/*.png'
